// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_setting
void ui_setting_screen_init(void);
lv_obj_t *ui_setting;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Label9;
void ui_event_Switch5(lv_event_t *e);
lv_obj_t *ui_Switch5;
void ui_event_Switch6(lv_event_t *e);
lv_obj_t *ui_Switch6;
void ui_event_Switch7(lv_event_t *e);
lv_obj_t *ui_Switch7;
void ui_event_Switch8(lv_event_t *e);
lv_obj_t *ui_Switch8;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label13;
void ui_event_Button5(lv_event_t *e);
lv_obj_t *ui_Button5;
lv_obj_t *ui_Container19;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Image21;
void ui_event_Button3(lv_event_t *e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Container20;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Image22;

// SCREEN: ui_step1
void ui_step1_screen_init(void);
lv_obj_t *ui_step1;
lv_obj_t *ui_Button12;
lv_obj_t *ui_Container2;
lv_obj_t *ui_Label20;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label23;
void ui_event_Button11(lv_event_t *e);
lv_obj_t *ui_Button11;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Label26;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Label28;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Button13;
void ui_event_Container3(lv_event_t *e);
lv_obj_t *ui_Container3;
lv_obj_t *ui_Label21;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Container11;
lv_obj_t *ui_Label43;
lv_obj_t *ui_step1itemselected;
lv_obj_t *ui_Image13;
lv_obj_t *ui_linestep4;

// SCREEN: ui_step3
void ui_step3_screen_init(void);
lv_obj_t *ui_step3;
void ui_event_Button1(lv_event_t *e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Container4;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label33;
void ui_event_Button15(lv_event_t *e);
lv_obj_t *ui_Button15;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Image8;
lv_obj_t *ui_Label35;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Button17;
lv_obj_t *ui_Button18;
lv_obj_t *ui_Button19;
lv_obj_t *ui_Label36;
lv_obj_t *ui_ContentProductInfo;
lv_obj_t *ui_Label37;
lv_obj_t *ui_Label38;
lv_obj_t *ui_Container10;
lv_obj_t *ui_Label39;
lv_obj_t *ui_Label44;
lv_obj_t *ui_Label45;
lv_obj_t *ui_Container12;
lv_obj_t *ui_Label46;
lv_obj_t *ui_Label47;
void ui_event_Button16(lv_event_t *e);
lv_obj_t *ui_Button16;
lv_obj_t *ui_Container7;
lv_obj_t *ui_Label40;
lv_obj_t *ui_Image9;
lv_obj_t *ui_Container8;
lv_obj_t *ui_Label31;
lv_obj_t *ui_step3itemselected;
lv_obj_t *ui_Image10;
lv_obj_t *ui_linestep2;
lv_obj_t *ui_Container9;
lv_obj_t *ui_Label41;
lv_obj_t *ui_Label42;
lv_obj_t *ui_Image11;
lv_obj_t *ui_linestep1;
lv_obj_t *ui_Image12;

// SCREEN: ui_step4
void ui_step4_screen_init(void);
lv_obj_t *ui_step4;
void ui_event_Button20(lv_event_t *e);
lv_obj_t *ui_Button20;
lv_obj_t *ui_Container13;
lv_obj_t *ui_Label48;
lv_obj_t *ui_Image14;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Label49;
lv_obj_t *ui_Label51;
void ui_event_ImgButton2(lv_event_t *e);
lv_obj_t *ui_ImgButton2;
lv_obj_t *ui_Container15;
lv_obj_t *ui_Image19;
lv_obj_t *ui_Label53;
lv_obj_t *ui_ImgButton3;
void ui_event_Button25(lv_event_t *e);
lv_obj_t *ui_Button25;
void ui_event_Container16(lv_event_t *e);
lv_obj_t *ui_Container16;
lv_obj_t *ui_Label61;
lv_obj_t *ui_Image16;
lv_obj_t *ui_Container17;
lv_obj_t *ui_Label62;
lv_obj_t *ui_step4itemselected;
lv_obj_t *ui_Image17;
lv_obj_t *ui_linestep3;
lv_obj_t *ui_Container18;
lv_obj_t *ui_Label64;
lv_obj_t *ui_Label65;
lv_obj_t *ui_Image18;
lv_obj_t *ui_linestep5;
lv_obj_t *ui_Container14;
lv_obj_t *ui_Label50;
lv_obj_t *ui_Label52;
lv_obj_t *ui_Image15;
lv_obj_t *ui_linestep6;

// SCREEN: ui_success
void ui_success_screen_init(void);
lv_obj_t *ui_success;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_line;
void ui_event_Button9(lv_event_t *e);
lv_obj_t *ui_Button9;
lv_obj_t *ui_Label4;
void ui_event_Button10(lv_event_t *e);
lv_obj_t *ui_Button10;
lv_obj_t *ui_Label16;
void ui_event_Button14(lv_event_t *e);
lv_obj_t *ui_Button14;
lv_obj_t *ui_Container5;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Image6;
void ui_event_Button8(lv_event_t *e);
lv_obj_t *ui_Button8;
lv_obj_t *ui_Container6;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Image7;

lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_image_[1] = {&ui_img_image_17_png};
const lv_img_dsc_t *ui_imgset_rectangle_[1] = {&ui_img_rectangle_7_png};

// SCREEN: ui_home1
void ui_home1_screen_init(void);
lv_obj_t *ui_home1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Container1;
void ui_event_Button201(lv_event_t *e);
lv_obj_t *ui_Button201;
lv_obj_t *ui_Image10;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label5;
void ui_event_Button202(lv_event_t *e);
lv_obj_t *ui_Button202;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label28;
void ui_event_Button203(lv_event_t *e);
lv_obj_t *ui_Button203;
lv_obj_t *ui_Image13;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Label30;
void ui_event_Button101(lv_event_t *e);
lv_obj_t *ui_Button101;
lv_obj_t *ui_Container11;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Image12;
lv_obj_t *ui_Scrolldots;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel3;

// SCREEN: ui_PickItems
void ui_PickItems_screen_init(void);
lv_obj_t *ui_PickItems;
void ui_event_Button104(lv_event_t *e);
lv_obj_t *ui_Button104;
lv_obj_t *ui_Container4;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Image4;
void ui_event_Button105(lv_event_t *e);
lv_obj_t *ui_Button105;
lv_obj_t *ui_Container5;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Container6;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Label19;
lv_obj_t *ui_linestep;
lv_obj_t *ui_Panel10;
lv_obj_t *ui_Label20;
lv_obj_t *ui_Label21;
lv_obj_t *ui_Container7;
void ui_event_Button106(lv_event_t *e);
lv_obj_t *ui_Button106;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Image7;
void ui_event_Button107(lv_event_t *e);
lv_obj_t *ui_Button107;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Image6;
void ui_event_Button108(lv_event_t *e);
lv_obj_t *ui_Button108;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Image8;
lv_obj_t *ui_Button109;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Panel11;
void ui_event_Button110(lv_event_t *e);
lv_obj_t *ui_Button110;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Button111;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Button112;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Button113;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label6;
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch5(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        setting_repid_fire(e);
    }
}
void ui_event_Switch6(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        setting_blower(e);
    }
}
void ui_event_Switch7(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        setting_vacuum(e);
    }
}
void ui_event_Switch8(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        setting_air_shot(e);
    }
}
void ui_event_Button5(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_step4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_step4_screen_init);
    }
}
void ui_event_Button3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home1_screen_init);
    }
}
void ui_event_Button11(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        load_to_shoot(e);
        _ui_screen_change(&ui_step3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_step3_screen_init);
    }
}
void ui_event_Container3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_init);
    }
}
void ui_event_Button1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_step1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_step1_screen_init);
    }
}
void ui_event_Button15(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        ready_for_launch(e);
        _ui_screen_change(&ui_step4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_step4_screen_init);
    }
}
void ui_event_Button16(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_init);
    }
}
void ui_event_Button20(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_step3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_step3_screen_init);
    }
}
void ui_event_ImgButton2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        launch_product(e);
        _ui_screen_change(&ui_success, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_success_screen_init);
    }
}
void ui_event_Button25(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_init);
    }
}
void ui_event_Container16(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_init);
    }
}
void ui_event_Button9(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        return_capsule(e);
        _ui_screen_change(&ui_step1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_step1_screen_init);
    }
}
void ui_event_Button10(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home1_screen_init);
    }
}
void ui_event_Button14(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_step4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_step4_screen_init);
    }
}
void ui_event_Button8(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_init);
    }
}
///////////////////// SCREENS HOME ////////////////////
void ui_event_Button201(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        home_short_pass(e);
    }
}
void ui_event_Button202(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        home_cannon(e);
    }
}
void ui_event_Button203(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        home_butler_delivery(e);
    }
}
void ui_event_Button101(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_init);
    }
}
void ui_event_Button104(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home1_screen_init);
    }
}
void ui_event_Button105(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setting_screen_init);
    }
}
void ui_event_Button106(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        select_alcohol(e);
    }
}
void ui_event_Button107(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        select_non_alcohol(e);
    }
}
void ui_event_Button108(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        select_snack(e);
    }
}
void ui_event_Button110(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        selected_items(e);
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_setting_screen_init();
    ui_step1_screen_init();
    ui_step3_screen_init();
    ui_step4_screen_init();
    ui_success_screen_init();
    // screens home
    ui_home1_screen_init();
    ui_PickItems_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_step1);
}
