// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_setting
void ui_setting_screen_init(void);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label9;
void ui_event_Switch5(lv_event_t * e);
extern lv_obj_t * ui_Switch5;
void ui_event_Switch6(lv_event_t * e);
extern lv_obj_t * ui_Switch6;
void ui_event_Switch7(lv_event_t * e);
extern lv_obj_t * ui_Switch7;
void ui_event_Switch8(lv_event_t * e);
extern lv_obj_t * ui_Switch8;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image21;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image22;
// SCREEN: ui_step1
void ui_step1_screen_init(void);
extern lv_obj_t * ui_step1;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label23;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Button13;
void ui_event_Container3(lv_event_t * e);
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_step1itemselected;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_linestep4;
// SCREEN: ui_step3
void ui_step3_screen_init(void);
extern lv_obj_t * ui_step3;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label33;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_ContentProductInfo;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_step3itemselected;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_linestep2;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_linestep1;
extern lv_obj_t * ui_Image12;
// SCREEN: ui_step4
void ui_step4_screen_init(void);
extern lv_obj_t * ui_step4;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label51;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_ImgButton3;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
void ui_event_Container16(lv_event_t * e);
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_step4itemselected;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_linestep3;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_linestep5;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_linestep6;
// SCREEN: ui_success
void ui_success_screen_init(void);
extern lv_obj_t * ui_success;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_line;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label4;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label16;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Image6;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image7;
// SCREEN: ui_home1
void ui_home1_screen_init(void);
extern lv_obj_t * ui_home1;
extern lv_obj_t * ui____initial_actions0;

// SCREEN: ui_home1
// SCREEN: ui_home1
void ui_home1_screen_init(void);
extern lv_obj_t * ui_home1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container1;
void ui_event_Button201(lv_event_t * e);
extern lv_obj_t * ui_Button201;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label5;
void ui_event_Button202(lv_event_t * e);
extern lv_obj_t * ui_Button202;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label28;
void ui_event_Button203(lv_event_t * e);
extern lv_obj_t * ui_Button203;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
void ui_event_Button101(lv_event_t * e);
extern lv_obj_t * ui_Button101;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Scrolldots;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
// SCREEN: ui_PickItems
void ui_PickItems_screen_init(void);
extern lv_obj_t * ui_PickItems;
void ui_event_Button104(lv_event_t * e);
extern lv_obj_t * ui_Button104;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image4;
void ui_event_Button105(lv_event_t * e);
extern lv_obj_t * ui_Button105;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_linestep;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Container7;
void ui_event_Button106(lv_event_t * e);
extern lv_obj_t * ui_Button106;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image7;
void ui_event_Button107(lv_event_t * e);
extern lv_obj_t * ui_Button107;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image6;
void ui_event_Button108(lv_event_t * e);
extern lv_obj_t * ui_Button108;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Button109;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel11;
void ui_event_Button110(lv_event_t * e);
extern lv_obj_t * ui_Button110;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Button111;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button112;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Button113;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label6;



LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_beer_corona_png);    // assets/beer_corona.png
LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_checked_png);    // assets/checked.png
LV_IMG_DECLARE(ui_img_corect_png);    // assets/corect.png
LV_IMG_DECLARE(ui_img_beer_corona_mini_png);    // assets/beer_corona_mini.png
LV_IMG_DECLARE(ui_img_lauch_btn_png);    // assets/lauch_btn.png
LV_IMG_DECLARE(ui_img_warning_png);    // assets/warning.png
LV_IMG_DECLARE(ui_img_image_17_png);    // assets/image 17.png
LV_IMG_DECLARE(ui_img_rectangle_7_png);    // assets/Rectangle 7.png
LV_IMG_DECLARE(ui_img_short_pass_png);    // assets/short_pass.png

LV_IMG_DECLARE(ui_img_short_pass_png);    // assets/short_pass.png
LV_IMG_DECLARE(ui_img_butler_delivery_png);    // assets/butler_delivery.png
LV_IMG_DECLARE(ui_img_alcohol_png);    // assets/alcohol.png
LV_IMG_DECLARE(ui_img_non_alcohol_png);    // assets/non_alcohol.png
LV_IMG_DECLARE(ui_img_snack_png);    // assets/snack.png
LV_IMG_DECLARE(ui_img_beer_png);    // assets/beer.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
