// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_step4_screen_init(void)
{
    ui_step4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_step4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button20 = lv_btn_create(ui_step4);
    lv_obj_set_width(ui_Button20, 46);
    lv_obj_set_height(ui_Button20, 22);
    lv_obj_set_x(ui_Button20, 24);
    lv_obj_set_y(ui_Button20, 0);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button20, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button20, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button20, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Button20);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 46);
    lv_obj_set_height(ui_Container13, 22);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label48 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label48, 21);
    lv_obj_set_height(ui_Label48, 14);
    lv_obj_set_x(ui_Label48, 20);
    lv_obj_set_y(ui_Label48, 6);
    lv_label_set_text(ui_Label48, "Back");
    lv_obj_set_style_text_font(ui_Label48, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Image14, &ui_img_back_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, 5);
    lv_obj_set_y(ui_Image14, 7);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_step4);
    lv_obj_set_width(ui_Panel4, 325);
    lv_obj_set_height(ui_Panel4, 367);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 115);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label49, "Setp 4");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0xF23A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 0);
    lv_obj_set_y(ui_Label51, 20);
    lv_label_set_text(ui_Label51, "Confirm and Shoot");
    lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label51, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_Panel4);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lauch_btn_png, NULL);
    lv_obj_set_height(ui_ImgButton2, 226);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, 36);
    lv_obj_set_y(ui_ImgButton2, 61);

    ui_Container15 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 153);
    lv_obj_set_height(ui_Container15, 28);
    lv_obj_set_x(ui_Container15, 75);
    lv_obj_set_y(ui_Container15, 294);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_img_create(ui_Container15);
    lv_img_set_src(ui_Image19, &ui_img_warning_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image19, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Image19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label53 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label53, 112);
    lv_obj_set_height(ui_Label53, 19);
    lv_obj_set_flex_flow(ui_Label53, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label53, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Label53, "Ensure face and hands are away from launch tube!!");
    lv_obj_set_style_text_align(ui_Label53, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_Panel4);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_beer_corona_mini_png, NULL);
    lv_obj_set_height(ui_ImgButton3, 63);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, 127);
    lv_obj_set_y(ui_ImgButton3, 108);

    ui_Button25 = lv_btn_create(ui_step4);
    lv_obj_set_width(ui_Button25, 60);
    lv_obj_set_height(ui_Button25, 22);
    lv_obj_set_x(ui_Button25, 243);
    lv_obj_set_y(ui_Button25, 0);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button25, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button25, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button25, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Button25);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 50);
    lv_obj_set_height(ui_Container16, 22);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container16, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label61, 40);
    lv_obj_set_height(ui_Label61, 14);
    lv_obj_set_x(ui_Label61, 15);
    lv_obj_set_y(ui_Label61, 6);
    lv_label_set_text(ui_Label61, "settings");
    lv_obj_set_style_text_font(ui_Label61, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_Container16);
    lv_img_set_src(ui_Image16, &ui_img_vector_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image16, -1);
    lv_obj_set_y(ui_Image16, 6);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container17 = lv_obj_create(ui_step4);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, 280);
    lv_obj_set_height(ui_Container17, 20);
    lv_obj_set_x(ui_Container17, 30);
    lv_obj_set_y(ui_Container17, 32);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label62 = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label62, "Step 1");
    lv_obj_set_style_text_color(ui_Label62, lv_color_hex(0xF23A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label62, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label62, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_step4itemselected = lv_label_create(ui_Container17);
    lv_obj_set_width(ui_step4itemselected, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_step4itemselected, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_step4itemselected, 34);
    lv_obj_set_y(ui_step4itemselected, -2);
    lv_label_set_text(ui_step4itemselected, "Cannon");
    lv_obj_set_style_text_font(ui_step4itemselected, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_img_create(ui_Container17);
    lv_img_set_src(ui_Image17, &ui_img_checked_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, 260);
    lv_obj_set_y(ui_Image17, 0);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_linestep3 = lv_btn_create(ui_Container17);
    lv_obj_set_width(ui_linestep3, 290);
    lv_obj_set_height(ui_linestep3, 2);
    lv_obj_set_x(ui_linestep3, 0);
    lv_obj_set_y(ui_linestep3, 10);
    lv_obj_set_align(ui_linestep3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_linestep3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_linestep3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_linestep3, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_linestep3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_linestep3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_linestep3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_step4);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 280);
    lv_obj_set_height(ui_Container18, 20);
    lv_obj_set_x(ui_Container18, 30);
    lv_obj_set_y(ui_Container18, 60);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label64 = lv_label_create(ui_Container18);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label64, "Step 2");
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0xF23A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label64, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Container18);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_Label65, 34);
    lv_obj_set_y(ui_Label65, -2);
    lv_label_set_text(ui_Label65, "Product Loaded");
    lv_obj_set_style_text_font(ui_Label65, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_img_create(ui_Container18);
    lv_img_set_src(ui_Image18, &ui_img_checked_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image18, 260);
    lv_obj_set_y(ui_Image18, 0);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_linestep5 = lv_btn_create(ui_Container18);
    lv_obj_set_width(ui_linestep5, 290);
    lv_obj_set_height(ui_linestep5, 2);
    lv_obj_set_x(ui_linestep5, 0);
    lv_obj_set_y(ui_linestep5, 10);
    lv_obj_set_align(ui_linestep5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_linestep5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_linestep5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_linestep5, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_linestep5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_linestep5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_linestep5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_step4);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 280);
    lv_obj_set_height(ui_Container14, 20);
    lv_obj_set_x(ui_Container14, 30);
    lv_obj_set_y(ui_Container14, 89);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label50 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label50, "Step 3");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0xF23A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_Label52, 34);
    lv_obj_set_y(ui_Label52, -2);
    lv_label_set_text(ui_Label52, "Ready for Launch");
    lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_img_create(ui_Container14);
    lv_img_set_src(ui_Image15, &ui_img_checked_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, 260);
    lv_obj_set_y(ui_Image15, 0);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_linestep6 = lv_btn_create(ui_Container14);
    lv_obj_set_width(ui_linestep6, 290);
    lv_obj_set_height(ui_linestep6, 2);
    lv_obj_set_x(ui_linestep6, 0);
    lv_obj_set_y(ui_linestep6, 10);
    lv_obj_set_align(ui_linestep6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_linestep6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_linestep6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_linestep6, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_linestep6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_linestep6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_linestep6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container16, ui_event_Container16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);

}
