// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_setting_screen_init(void)
{
    ui_setting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_setting);
    lv_obj_set_width(ui_Panel2, 294);
    lv_obj_set_height(ui_Panel2, 267);
    lv_obj_set_x(ui_Panel2, 13);
    lv_obj_set_y(ui_Panel2, 106);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 13);
    lv_label_set_text(ui_Label9, "Rapid fire");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, 200);
    lv_obj_set_y(ui_Switch5, 10);

    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Switch6 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_x(ui_Switch6, 200);
    lv_obj_set_y(ui_Switch6, 60);


    ui_Switch7 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_Switch7, 50);
    lv_obj_set_height(ui_Switch7, 25);
    lv_obj_set_x(ui_Switch7, 200);
    lv_obj_set_y(ui_Switch7, 117);


    ui_Switch8 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_Switch8, 50);
    lv_obj_set_height(ui_Switch8, 25);
    lv_obj_set_x(ui_Switch8, 200);
    lv_obj_set_y(ui_Switch8, 173);


    ui_Label10 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 61);
    lv_label_set_text(ui_Label10, "Continuous Blower");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, 122);
    lv_label_set_text(ui_Label11, "Continuous Vacuum");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, 183);
    lv_label_set_text(ui_Label12, "Compressed air shot");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_setting);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 27);
    lv_obj_set_y(ui_Label13, 44);
    lv_label_set_text(ui_Label13, "Settings");
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_setting);
    lv_obj_set_width(ui_Button5, 46);
    lv_obj_set_height(ui_Button5, 22);
    lv_obj_set_x(ui_Button5, 24);
    lv_obj_set_y(ui_Button5, 0);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_Button5);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 46);
    lv_obj_set_height(ui_Container19, 22);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_Label5, 21);
    lv_obj_set_height(ui_Label5, 14);
    lv_obj_set_x(ui_Label5, 20);
    lv_obj_set_y(ui_Label5, 7);
    lv_label_set_text(ui_Label5, "Back");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_img_create(ui_Container19);
    lv_img_set_src(ui_Image21, &ui_img_back_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image21, 5);
    lv_obj_set_y(ui_Image21, 7);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_setting);
    lv_obj_set_width(ui_Button3, 60);
    lv_obj_set_height(ui_Button3, 22);
    lv_obj_set_x(ui_Button3, 243);
    lv_obj_set_y(ui_Button3, 0);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container20 = lv_obj_create(ui_Button3);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_width(ui_Container20, 50);
    lv_obj_set_height(ui_Container20, 22);
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container20, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_Label6, 40);
    lv_obj_set_height(ui_Label6, 14);
    lv_obj_set_x(ui_Label6, 15);
    lv_obj_set_y(ui_Label6, 7);
    lv_label_set_text(ui_Label6, "Home");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image22 = lv_img_create(ui_Container20);
    lv_img_set_src(ui_Image22, &ui_img_home_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image22, -1);
    lv_obj_set_y(ui_Image22, 6);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Switch5, ui_event_Switch5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch6, ui_event_Switch6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch7, ui_event_Switch7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch8, ui_event_Switch8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
